//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFieldsTemplate
    {
        public int idContractFieldTemplate { get; set; }
        public int idContractType { get; set; }
        public bool MandatoryField { get; set; }
        public string DefaultValue { get; set; }
        public string AliasField { get; set; }
        public string FieldValue { get; set; }
        public int idContractFieldTypes { get; set; }
    
        public virtual BaseFieldType BaseFieldType { get; set; }
        public virtual BaseType BaseType { get; set; }
    }
}
