//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFieldType
    {
        public BaseFieldType()
        {
            this.BaseFieldsTemplates = new HashSet<BaseFieldsTemplate>();
        }
    
        public int IdContractFieldType { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<BaseFieldsTemplate> BaseFieldsTemplates { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
