//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base
    {
        public int IdContract { get; set; }
        public int IdContractType { get; set; }
        public int IdClient { get; set; }
        public int UserCreation { get; set; }
        public int UserUpdate { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual BaseType BaseType { get; set; }
    }
}
