//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractsRecollectEntities : DbContext
    {
        public ContractsRecollectEntities()
            : base("name=ContractsRecollectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base> Bases { get; set; }
        public virtual DbSet<BaseFieldsTemplate> BaseFieldsTemplates { get; set; }
        public virtual DbSet<BaseFieldType> BaseFieldTypes { get; set; }
        public virtual DbSet<BaseType> BaseTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
